-- Rollback: Add back the removed columns from blocks table
-- This is a rollback script in case we need to restore the full Ethereum block structure

ALTER TABLE blocks 
ADD COLUMN IF NOT EXISTS sha3_uncles VARCHAR(66) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS nonce VARCHAR(18) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS mix_hash VARCHAR(66) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS miner TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS state_root VARCHAR(66) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS transactions_root VARCHAR(66) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS receipts_root VARCHAR(66) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS logs_bloom TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS size BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS extra_data TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS difficulty NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_difficulty NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS gas_limit NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS gas_used NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS withdrawals_root VARCHAR(66) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS base_fee_per_gas BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS sign SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS insert_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
