-- Rollback: Add back the removed columns from transactions table
-- This is a rollback script in case we need to restore the full transaction structure

ALTER TABLE transactions 
ADD COLUMN IF NOT EXISTS block_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS transaction_index BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS gas BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS gas_price NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS data TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS function_selector VARCHAR(10) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS max_fee_per_gas NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_priority_fee_per_gas NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_fee_per_blob_gas NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS blob_versioned_hashes TEXT[] NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS r NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS s NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS v NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS access_list JSONB,
ADD COLUMN IF NOT EXISTS authorization_list JSONB,
ADD COLUMN IF NOT EXISTS contract_address TEXT,
ADD COLUMN IF NOT EXISTS gas_used BIGINT,
ADD COLUMN IF NOT EXISTS cumulative_gas_used BIGINT,
ADD COLUMN IF NOT EXISTS effective_gas_price NUMERIC,
ADD COLUMN IF NOT EXISTS blob_gas_used BIGINT,
ADD COLUMN IF NOT EXISTS blob_gas_price NUMERIC,
ADD COLUMN IF NOT EXISTS logs_bloom TEXT,
ADD COLUMN IF NOT EXISTS insert_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS sign TEXT;
