import { UUID } from "crypto";

export const ROUTES = {
  BLOCK: (number: number, queryParams?: string) => `/blocks/${number}${queryParams ? `?${queryParams}` : ''}`,
  BLOCKS: '/blocks',
  CAMPAIGN_EDIT: (slug: string) => `/donation-campaign/${slug}/edit`,
  CAMPAIGN: (slug: string) => `/donation-campaign/${slug}`,
  COBAR: '/cobar',
  CREATE_CAMPAIGN: '/donation-campaign/create',
  DEVELOPER: '/developer',
  DONATION_CAMPAIGN: '/donation-campaign',
  HOME: '/',
  LI_XI: '/li-xi',
  CREATE_LI_XI: '/li-xi/create',
  LI_XI_DETAIL: (id: UUID) => `/li-xi/${id}`,
  MEZON_GAME: '/mezon-game',
  PENDING_TRANSACTION: (hash: string) => `/transactions/pending/${hash}`,
  PROFILE: '/profile',
  STAKE: '/stake',
  SWAP: '/swap',
  TRANSACTION: (hash: string, queryParams?: string) => `/transactions/${hash}${queryParams ? `?${queryParams}` : ''}`,
  TRANSACTIONS: '/transactions',
  TRANSFER: '/transfer',
  WALLET: (address: string, queryParams?: string) => `/wallets/${address}${queryParams ? `?${queryParams}` : ''}`,
  WALLETS: '/wallets',
} as const;
