package cmd

import (
	"os"

	configs "github.com/mezonai/mmn-tx-explorer/indexer/configs"
	customLogger "github.com/mezonai/mmn-tx-explorer/indexer/internal/log"
	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var (
	// Used for flags.
	cfgFile string

	rootCmd = &cobra.Command{
		Use:   "indexer",
		Short: "TBD",
		Long:  "TBD",
		Run: func(cmd *cobra.Command, args []string) {
			go func() {
				RunOrchestrator(cmd, args)
			}()
			RunAPI(cmd, args)
		},
	}
)

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func init() {
	cobra.OnInitialize(initConfig)

	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is ./configs/config.yml)")
	rootCmd.PersistentFlags().String("rpc-url", "", "RPC Url to use for the indexer")
	rootCmd.PersistentFlags().Int("rpc-blocks-blocksPerRequest", 0, "How many blocks to fetch per request")
	rootCmd.PersistentFlags().Int("rpc-blocks-batchDelay", 0, "Milliseconds to wait between batches of blocks when fetching from the RPC")
	rootCmd.PersistentFlags().Int("rpc-logs-blocksPerRequest", 0, "How many blocks to fetch logs per request")
	rootCmd.PersistentFlags().Int("rpc-logs-batchDelay", 0, "Milliseconds to wait between batches of logs when fetching from the RPC")
	rootCmd.PersistentFlags().Bool("rpc-blockReceipts-enabled", false, "Whether to enable fetching block receipts from the RPC")
	rootCmd.PersistentFlags().Int("rpc-blockReceipts-blocksPerRequest", 0, "How many blocks to fetch receipts for per request")
	rootCmd.PersistentFlags().Int("rpc-blockReceipts-batchDelay", 0, "Milliseconds to wait between batches of receipts when fetching from the RPC")
	rootCmd.PersistentFlags().Bool("rpc-traces-enabled", true, "Whether to enable fetching traces from the RPC")
	rootCmd.PersistentFlags().Int("rpc-traces-blocksPerRequest", 0, "How many blocks to fetch traces per request")
	rootCmd.PersistentFlags().Int("rpc-traces-batchDelay", 0, "Milliseconds to wait between batches of traces when fetching from the RPC")
	rootCmd.PersistentFlags().String("log-level", "", "Log level to use for the application")
	rootCmd.PersistentFlags().Bool("log-prettify", false, "Whether to prettify the log output")
	rootCmd.PersistentFlags().Bool("poller-enabled", true, "Toggle poller")
	rootCmd.PersistentFlags().Bool("poller-interval", true, "Poller interval")
	rootCmd.PersistentFlags().Int("poller-blocks-per-poll", 10, "How many blocks to poll each interval")
	rootCmd.PersistentFlags().Int("poller-from-block", 0, "From which block to start polling")
	rootCmd.PersistentFlags().Bool("poller-force-from-block", false, "Force the poller to start from the block specified in `poller-from-block`")
	rootCmd.PersistentFlags().Int("poller-until-block", 0, "Until which block to poll")
	rootCmd.PersistentFlags().Int("poller-parallel-pollers", 5, "Maximum number of parallel pollers")
	rootCmd.PersistentFlags().Bool("committer-enabled", true, "Toggle committer")
	rootCmd.PersistentFlags().Int("committer-blocks-per-commit", 10, "How many blocks to commit each interval")
	rootCmd.PersistentFlags().Int("committer-interval", 1000, "How often to commit blocks in milliseconds")
	rootCmd.PersistentFlags().Int("committer-from-block", 0, "From which block to start committing")
	rootCmd.PersistentFlags().Bool("reorgHandler-enabled", true, "Toggle reorg handler")
	rootCmd.PersistentFlags().Int("reorgHandler-interval", 1000, "How often to run reorg handler in milliseconds")
	rootCmd.PersistentFlags().Int("reorgHandler-blocks-per-scan", 100, "How many blocks to scan for reorgs")
	rootCmd.PersistentFlags().Int("reorgHandler-from-block", 0, "From which block to start scanning for reorgs")
	rootCmd.PersistentFlags().Bool("reorgHandler-force-from-block", false, "Force the reorg handler to start from the block specified in `reorgHandler-from-block`")
	rootCmd.PersistentFlags().Bool("failure-recoverer-enabled", true, "Toggle failure recoverer")
	rootCmd.PersistentFlags().Int("failure-recoverer-blocks-per-run", 10, "How many blocks to run failure recoverer for")
	rootCmd.PersistentFlags().Int("failure-recoverer-interval", 1000, "How often to run failure recoverer in milliseconds")
	rootCmd.PersistentFlags().String("storage-orchestrator-postgres-host", "", "PostgreSQL host for orchestrator storage")
	rootCmd.PersistentFlags().Int("storage-orchestrator-postgres-port", 5432, "PostgreSQL port for orchestrator storage")
	rootCmd.PersistentFlags().String("storage-orchestrator-postgres-username", "", "PostgreSQL username for orchestrator storage")
	rootCmd.PersistentFlags().String("storage-orchestrator-postgres-password", "", "PostgreSQL password for orchestrator storage")
	rootCmd.PersistentFlags().String("storage-orchestrator-postgres-database", "", "PostgreSQL database for orchestrator storage")
	rootCmd.PersistentFlags().String("storage-orchestrator-postgres-sslMode", "require", "PostgreSQL SSL mode for orchestrator storage (disable, require, verify-ca, verify-full)")
	rootCmd.PersistentFlags().Int("storage-orchestrator-postgres-maxOpenConns", 50, "PostgreSQL max open connections for orchestrator storage")
	rootCmd.PersistentFlags().Int("storage-orchestrator-postgres-maxIdleConns", 25, "PostgreSQL max idle connections for orchestrator storage")
	rootCmd.PersistentFlags().Int("storage-orchestrator-postgres-maxConnLifetime", 300, "PostgreSQL max connection lifetime in seconds for orchestrator storage")
	rootCmd.PersistentFlags().Int("storage-orchestrator-postgres-connectTimeout", 10, "PostgreSQL connection timeout in seconds for orchestrator storage")
	rootCmd.PersistentFlags().String("storage-staging-postgres-host", "", "PostgreSQL host for staging storage")
	rootCmd.PersistentFlags().Int("storage-staging-postgres-port", 5432, "PostgreSQL port for staging storage")
	rootCmd.PersistentFlags().String("storage-staging-postgres-username", "", "PostgreSQL username for staging storage")
	rootCmd.PersistentFlags().String("storage-staging-postgres-password", "", "PostgreSQL password for staging storage")
	rootCmd.PersistentFlags().String("storage-staging-postgres-database", "", "PostgreSQL database for staging storage")
	rootCmd.PersistentFlags().String("storage-staging-postgres-sslMode", "require", "PostgreSQL SSL mode for staging storage (disable, require, verify-ca, verify-full)")
	rootCmd.PersistentFlags().Int("storage-staging-postgres-maxOpenConns", 50, "PostgreSQL max open connections for staging storage")
	rootCmd.PersistentFlags().Int("storage-staging-postgres-maxIdleConns", 25, "PostgreSQL max idle connections for staging storage")
	rootCmd.PersistentFlags().Int("storage-staging-postgres-maxConnLifetime", 300, "PostgreSQL max connection lifetime in seconds for staging storage")
	rootCmd.PersistentFlags().Int("storage-staging-postgres-connectTimeout", 10, "PostgreSQL connection timeout in seconds for staging storage")
	rootCmd.PersistentFlags().String("storage-main-clickhouse-host", "", "ClickHouse host")
	rootCmd.PersistentFlags().Int("storage-main-clickhouse-port", 9000, "ClickHouse port")
	rootCmd.PersistentFlags().String("storage-main-clickhouse-username", "", "ClickHouse username")
	rootCmd.PersistentFlags().String("storage-main-clickhouse-password", "", "ClickHouse password")
	rootCmd.PersistentFlags().String("storage-main-clickhouse-database", "", "ClickHouse database")
	rootCmd.PersistentFlags().String("storage-main-clickhouse-sslMode", "disable", "ClickHouse SSL mode (enable, disable)")
	rootCmd.PersistentFlags().Int("storage-main-clickhouse-maxOpenConns", 50, "ClickHouse max open connections")
	rootCmd.PersistentFlags().Int("storage-main-clickhouse-maxIdleConns", 25, "ClickHouse max idle connections")
	rootCmd.PersistentFlags().Int("storage-main-clickhouse-maxConnLifetime", 300, "ClickHouse max connection lifetime in seconds")
	rootCmd.PersistentFlags().Int("storage-main-clickhouse-connectTimeout", 10, "ClickHouse connection timeout in seconds")
	rootCmd.PersistentFlags().String("api-host", "localhost:8080", "API host")
	rootCmd.PersistentFlags().String("api-basicAuth-username", "", "API basic auth username")
	rootCmd.PersistentFlags().String("api-basicAuth-password", "", "API basic auth password")
	rootCmd.PersistentFlags().String("api-thirdweb-clientId", "", "Thirdweb client id")
	rootCmd.PersistentFlags().Int("api-contractApiRequest-maxIdleConns", 100, "Max idle connections for contract API request")
	rootCmd.PersistentFlags().Int("api-contractApiRequest-maxIdleConnsPerHost", 100, "Max idle connections per host for contract API request")
	rootCmd.PersistentFlags().Int("api-contractApiRequest-maxConnsPerHost", 100, "Max connections per host for contract API request")
	rootCmd.PersistentFlags().Int("api-contractApiRequest-idleConnTimeout", 90, "Idle connection timeout for contract API request in seconds")
	rootCmd.PersistentFlags().Bool("api-contractApiRequest-disableCompression", false, "Disable compression for contract API request")
	rootCmd.PersistentFlags().Int("api-contractApiRequest-timeout", 10, "Timeout in seconds for contract API request")
	rootCmd.PersistentFlags().Bool("publisher-enabled", false, "Toggle publisher")
	rootCmd.PersistentFlags().String("publisher-mode", "default", "Publisher mode: default or parallel")
	rootCmd.PersistentFlags().String("publisher-brokers", "", "Kafka brokers")
	rootCmd.PersistentFlags().Bool("publisher-blocks-enabled", false, "Toggle block publisher")
	rootCmd.PersistentFlags().String("publisher-blocks-topicName", "", "Kafka topic name for blocks")
	rootCmd.PersistentFlags().Bool("publisher-transactions-enabled", false, "Toggle transaction publisher")
	rootCmd.PersistentFlags().String("publisher-transactions-topicName", "", "Kafka topic name for transactions")
	rootCmd.PersistentFlags().String("publisher-transactions-toFilter", "", "Filter transactions by to address")
	rootCmd.PersistentFlags().String("publisher-transactions-fromFilter", "", "Filter transactions by from address")
	rootCmd.PersistentFlags().Bool("publisher-traces-enabled", false, "Toggle trace publisher")
	rootCmd.PersistentFlags().String("publisher-traces-topicName", "", "Kafka topic name for traces")
	rootCmd.PersistentFlags().Bool("publisher-events-enabled", false, "Toggle event publisher")
	rootCmd.PersistentFlags().String("publisher-events-topicName", "", "Kafka topic name for events")
	rootCmd.PersistentFlags().String("publisher-events-addressFilter", "", "Filter events by address")
	rootCmd.PersistentFlags().String("publisher-events-topic0Filter", "", "Filter events by topic0")
	rootCmd.PersistentFlags().Int("workMode-checkIntervalMinutes", 10, "How often to check work mode in minutes")
	rootCmd.PersistentFlags().Int64("workMode-liveModeThreshold", 500, "How many blocks the indexer can be behind before switching to live mode")
	rootCmd.PersistentFlags().String("validation-mode", "strict", "Validation mode. Strict will validate logsBloom and transactionsRoot. Minimal will validate transaction count and logs existence.")
	rootCmd.PersistentFlags().Bool("stats-worker-enabled", true, "Enable stats recalculation worker")
	rootCmd.PersistentFlags().Int("stats-worker-interval", 120, "Stats recalculation interval in minutes")
	viperBindFlag("rpc.url", "rpc-url")
	viperBindFlag("rpc.blocks.blocksPerRequest", "rpc-blocks-blocksPerRequest")
	viperBindFlag("rpc.blocks.batchDelay", "rpc-blocks-batchDelay")
	viperBindFlag("rpc.logs.blocksPerRequest", "rpc-logs-blocksPerRequest")
	viperBindFlag("rpc.logs.batchDelay", "rpc-logs-batchDelay")
	viperBindFlag("rpc.blockReceipts.enabled", "rpc-blockReceipts-enabled")
	viperBindFlag("rpc.blockReceipts.blocksPerRequest", "rpc-blockReceipts-blocksPerRequest")
	viperBindFlag("rpc.blockReceipts.batchDelay", "rpc-blockReceipts-batchDelay")
	viperBindFlag("rpc.traces.enabled", "rpc-traces-enabled")
	viperBindFlag("rpc.traces.blocksPerRequest", "rpc-traces-blocksPerRequest")
	viperBindFlag("rpc.traces.batchDelay", "rpc-traces-batchDelay")
	viperBindFlag("log.level", "log-level")
	viperBindFlag("log.prettify", "log-prettify")
	viperBindFlag("poller.enabled", "poller-enabled")
	viperBindFlag("poller.interval", "poller-interval")
	viperBindFlag("poller.blocksPerPoll", "poller-blocks-per-poll")
	viperBindFlag("poller.fromBlock", "poller-from-block")
	viperBindFlag("poller.forceFromBlock", "poller-force-from-block")
	viperBindFlag("poller.untilBlock", "poller-until-block")
	viperBindFlag("poller.parallelPollers", "poller-parallel-pollers")
	viperBindFlag("committer.enabled", "committer-enabled")
	viperBindFlag("committer.blocksPerCommit", "committer-blocks-per-commit")
	viperBindFlag("committer.interval", "committer-interval")
	viperBindFlag("committer.fromBlock", "committer-from-block")
	viperBindFlag("reorgHandler.enabled", "reorgHandler-enabled")
	viperBindFlag("reorgHandler.interval", "reorgHandler-interval")
	viperBindFlag("reorgHandler.blocksPerScan", "reorgHandler-blocks-per-scan")
	viperBindFlag("reorgHandler.fromBlock", "reorgHandler-from-block")
	viperBindFlag("reorgHandler.forceFromBlock", "reorgHandler-force-from-block")
	viperBindFlag("failureRecoverer.enabled", "failure-recoverer-enabled")
	viperBindFlag("failureRecoverer.blocksPerRun", "failure-recoverer-blocks-per-run")
	viperBindFlag("failureRecoverer.interval", "failure-recoverer-interval")
	viperBindFlag("storage.orchestrator.postgres.host", "storage-orchestrator-postgres-host")
	viperBindFlag("storage.orchestrator.postgres.port", "storage-orchestrator-postgres-port")
	viperBindFlag("storage.orchestrator.postgres.username", "storage-orchestrator-postgres-username")
	viperBindFlag("storage.orchestrator.postgres.password", "storage-orchestrator-postgres-password")
	viperBindFlag("storage.orchestrator.postgres.database", "storage-orchestrator-postgres-database")
	viperBindFlag("storage.orchestrator.postgres.sslMode", "storage-orchestrator-postgres-sslMode")
	viperBindFlag("storage.orchestrator.postgres.maxOpenConns", "storage-orchestrator-postgres-maxOpenConns")
	viperBindFlag("storage.orchestrator.postgres.maxIdleConns", "storage-orchestrator-postgres-maxIdleConns")
	viperBindFlag("storage.orchestrator.postgres.maxConnLifetime", "storage-orchestrator-postgres-maxConnLifetime")
	viperBindFlag("storage.orchestrator.postgres.connectTimeout", "storage-orchestrator-postgres-connectTimeout")
	viperBindFlag("storage.staging.postgres.host", "storage-staging-postgres-host")
	viperBindFlag("storage.staging.postgres.port", "storage-staging-postgres-port")
	viperBindFlag("storage.staging.postgres.username", "storage-staging-postgres-username")
	viperBindFlag("storage.staging.postgres.password", "storage-staging-postgres-password")
	viperBindFlag("storage.staging.postgres.database", "storage-staging-postgres-database")
	viperBindFlag("storage.staging.postgres.sslMode", "storage-staging-postgres-sslMode")
	viperBindFlag("storage.staging.postgres.maxOpenConns", "storage-staging-postgres-maxOpenConns")
	viperBindFlag("storage.staging.postgres.maxIdleConns", "storage-staging-postgres-maxIdleConns")
	viperBindFlag("storage.staging.postgres.maxConnLifetime", "storage-staging-postgres-maxConnLifetime")
	viperBindFlag("storage.staging.postgres.connectTimeout", "storage-staging-postgres-connectTimeout")
	viperBindFlag("storage.main.clickhouse.host", "storage-main-clickhouse-host")
	viperBindFlag("storage.main.clickhouse.port", "storage-main-clickhouse-port")
	viperBindFlag("storage.main.clickhouse.username", "storage-main-clickhouse-username")
	viperBindFlag("storage.main.clickhouse.password", "storage-main-clickhouse-password")
	viperBindFlag("storage.main.clickhouse.database", "storage-main-clickhouse-database")
	viperBindFlag("storage.main.clickhouse.sslMode", "storage-main-clickhouse-sslMode")
	viperBindFlag("storage.main.clickhouse.maxOpenConns", "storage-main-clickhouse-maxOpenConns")
	viperBindFlag("storage.main.clickhouse.maxIdleConns", "storage-main-clickhouse-maxIdleConns")
	viperBindFlag("storage.main.clickhouse.maxConnLifetime", "storage-main-clickhouse-maxConnLifetime")
	viperBindFlag("storage.main.clickhouse.connectTimeout", "storage-main-clickhouse-connectTimeout")
	viperBindFlag("api.host", "api-host")
	viperBindFlag("api.basicAuth.username", "api-basicAuth-username")
	viperBindFlag("api.basicAuth.password", "api-basicAuth-password")
	viperBindFlag("api.thirdweb.clientId", "api-thirdweb-clientId")
	viperBindFlag("api.contractApiRequest.maxIdleConns", "api-contractApiRequest-maxIdleConns")
	viperBindFlag("api.contractApiRequest.maxIdleConnsPerHost", "api-contractApiRequest-maxIdleConnsPerHost")
	viperBindFlag("api.contractApiRequest.maxConnsPerHost", "api-contractApiRequest-maxConnsPerHost")
	viperBindFlag("api.contractApiRequest.idleConnTimeout", "api-contractApiRequest-idleConnTimeout")
	viperBindFlag("api.contractApiRequest.disableCompression", "api-contractApiRequest-disableCompression")
	viperBindFlag("api.contractApiRequest.timeout", "api-contractApiRequest-timeout")
	viperBindFlag("publisher.enabled", "publisher-enabled")
	viperBindFlag("publisher.mode", "publisher-mode")
	viperBindFlag("publisher.brokers", "publisher-brokers")
	viperBindFlag("publisher.blocks.enabled", "publisher-blocks-enabled")
	viperBindFlag("publisher.blocks.topicName", "publisher-blocks-topicName")
	viperBindFlag("publisher.transactions.enabled", "publisher-transactions-enabled")
	viperBindFlag("publisher.transactions.topicName", "publisher-transactions-topicName")
	viperBindFlag("publisher.transactions.toFilter", "publisher-transactions-toFilter")
	viperBindFlag("publisher.transactions.fromFilter", "publisher-transactions-fromFilter")
	viperBindFlag("publisher.traces.enabled", "publisher-traces-enabled")
	viperBindFlag("publisher.traces.topicName", "publisher-traces-topicName")
	viperBindFlag("publisher.events.enabled", "publisher-events-enabled")
	viperBindFlag("publisher.events.topicName", "publisher-events-topicName")
	viperBindFlag("publisher.events.addressFilter", "publisher-events-addressFilter")
	viperBindFlag("publisher.events.topic0Filter", "publisher-events-topic0Filter")
	viperBindFlag("workMode.checkIntervalMinutes", "workMode-checkIntervalMinutes")
	viperBindFlag("workMode.liveModeThreshold", "workMode-liveModeThreshold")
	viperBindFlag("statsWorker.intervalMinutes", "stats-worker-interval")
	viperBindFlag("validation.mode", "validation-mode")
	rootCmd.AddCommand(orchestratorCmd)
	rootCmd.AddCommand(apiCmd)
	rootCmd.AddCommand(validateAndFixCmd)
	rootCmd.AddCommand(validateCmd)
	rootCmd.AddCommand(migrateValidationCmd)
	rootCmd.AddCommand(migratePostgresCmd)
}

func initConfig() {
	err := configs.LoadConfig(cfgFile)
	if err != nil {
		log.Fatal().Err(err).Msgf("Failed to load config: %s", err.Error())
	}
	customLogger.InitLogger()
}

func viperBindFlag(flagName, lookupFlagName string) {
	err := viper.BindPFlag(flagName, rootCmd.PersistentFlags().Lookup(lookupFlagName))
	if err != nil {
		log.Fatal().Err(err).Msgf("Failed to bind flag %s: %s", flagName, err.Error())
	}
}
