# Server Configuration
server:
  host: 0.0.0.0
  port: 8899
  gin_mode: debug

database:
  host: dpg-d4j89g6r433s7396vj60-a.oregon-postgres.render.com
  port: 5432
  username: trongngovan
  password: EeDUa5dpnnt4gAK1PFEumUgcjQmRejc2
  name: mmn_explorer
  schema: mezon
  sslmode: require
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 300
  conn_max_idle_time: 60

jwt:
  secret: "a75081d475a4cd4e130916f26e3e8d3ebc376fa132e873c057c5a0c5ab26cc06"
  api_key: "MezonDongServiceEventAPIKey2024!"

redis:
  address: 
  username: "default"
  password: ""
  db: 0

# Logging Configuration
logging:
  level: "info"           # debug, info, warn, error, fatal, panic
  output: "stdout"        # stdout or file
  file_path: "logs/socket-service.log"  # required when output=file
  max_size: 100           # max size in MB before rotation (default: 100)
  max_age: 30             # max age in days to retain old logs (default: 30)