// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v6.31.1
// source: account.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxMeta_Status int32

const (
	TxMeta_PENDING   TxMeta_Status = 0
	TxMeta_CONFIRMED TxMeta_Status = 1
	TxMeta_FINALIZED TxMeta_Status = 2
	TxMeta_FAILED    TxMeta_Status = 3
)

// Enum value maps for TxMeta_Status.
var (
	TxMeta_Status_name = map[int32]string{
		0: "PENDING",
		1: "CONFIRMED",
		2: "FINALIZED",
		3: "FAILED",
	}
	TxMeta_Status_value = map[string]int32{
		"PENDING":   0,
		"CONFIRMED": 1,
		"FINALIZED": 2,
		"FAILED":    3,
	}
)

func (x TxMeta_Status) Enum() *TxMeta_Status {
	p := new(TxMeta_Status)
	*p = x
	return p
}

func (x TxMeta_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxMeta_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[0].Descriptor()
}

func (TxMeta_Status) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[0]
}

func (x TxMeta_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxMeta_Status.Descriptor instead.
func (TxMeta_Status) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3, 0}
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance       uint64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAccountResponse) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetAccountResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type GetTxHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Filter        uint32                 `protobuf:"varint,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxHistoryRequest) Reset() {
	*x = GetTxHistoryRequest{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxHistoryRequest) ProtoMessage() {}

func (x *GetTxHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTxHistoryRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetTxHistoryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTxHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTxHistoryRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTxHistoryRequest) GetFilter() uint32 {
	if x != nil {
		return x.Filter
	}
	return 0
}

type TxMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`       // sender address
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"` // recipient address
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`      // amount
	Nonce         uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`        // nonce
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        TxMeta_Status          `protobuf:"varint,6,opt,name=status,proto3,enum=mmn.TxMeta_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxMeta) Reset() {
	*x = TxMeta{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxMeta) ProtoMessage() {}

func (x *TxMeta) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxMeta.ProtoReflect.Descriptor instead.
func (*TxMeta) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *TxMeta) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TxMeta) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *TxMeta) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TxMeta) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TxMeta) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TxMeta) GetStatus() TxMeta_Status {
	if x != nil {
		return x.Status
	}
	return TxMeta_PENDING
}

type GetTxHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Txs           []*TxMeta              `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxHistoryResponse) Reset() {
	*x = GetTxHistoryResponse{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxHistoryResponse) ProtoMessage() {}

func (x *GetTxHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTxHistoryResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetTxHistoryResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTxHistoryResponse) GetTxs() []*TxMeta {
	if x != nil {
		return x.Txs
	}
	return nil
}

type GetCurrentNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"` // "latest" or "pending"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentNonceRequest) Reset() {
	*x = GetCurrentNonceRequest{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentNonceRequest) ProtoMessage() {}

func (x *GetCurrentNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentNonceRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentNonceRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrentNonceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetCurrentNonceRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetCurrentNonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentNonceResponse) Reset() {
	*x = GetCurrentNonceResponse{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentNonceResponse) ProtoMessage() {}

func (x *GetCurrentNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentNonceResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentNonceResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *GetCurrentNonceResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetCurrentNonceResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *GetCurrentNonceResponse) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetCurrentNonceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\x03mmn\"-\n" +
	"\x11GetAccountRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"^\n" +
	"\x12GetAccountResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x04R\abalance\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\"u\n" +
	"\x13GetTxHistoryRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\rR\x06filter\"\xf7\x01\n" +
	"\x06TxMeta\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12*\n" +
	"\x06status\x18\x06 \x01(\x0e2\x12.mmn.TxMeta.StatusR\x06status\"?\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\r\n" +
	"\tFINALIZED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\"K\n" +
	"\x14GetTxHistoryResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x1d\n" +
	"\x03txs\x18\x02 \x03(\v2\v.mmn.TxMetaR\x03txs\"D\n" +
	"\x16GetCurrentNonceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"q\n" +
	"\x17GetCurrentNonceResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xe2\x01\n" +
	"\x0eAccountService\x12=\n" +
	"\n" +
	"GetAccount\x12\x16.mmn.GetAccountRequest\x1a\x17.mmn.GetAccountResponse\x12C\n" +
	"\fGetTxHistory\x12\x18.mmn.GetTxHistoryRequest\x1a\x19.mmn.GetTxHistoryResponse\x12L\n" +
	"\x0fGetCurrentNonce\x12\x1b.mmn.GetCurrentNonceRequest\x1a\x1c.mmn.GetCurrentNonceResponseB\x11Z\x0fmmn/proto;protob\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_account_proto_goTypes = []any{
	(TxMeta_Status)(0),              // 0: mmn.TxMeta.Status
	(*GetAccountRequest)(nil),       // 1: mmn.GetAccountRequest
	(*GetAccountResponse)(nil),      // 2: mmn.GetAccountResponse
	(*GetTxHistoryRequest)(nil),     // 3: mmn.GetTxHistoryRequest
	(*TxMeta)(nil),                  // 4: mmn.TxMeta
	(*GetTxHistoryResponse)(nil),    // 5: mmn.GetTxHistoryResponse
	(*GetCurrentNonceRequest)(nil),  // 6: mmn.GetCurrentNonceRequest
	(*GetCurrentNonceResponse)(nil), // 7: mmn.GetCurrentNonceResponse
}
var file_account_proto_depIdxs = []int32{
	0, // 0: mmn.TxMeta.status:type_name -> mmn.TxMeta.Status
	4, // 1: mmn.GetTxHistoryResponse.txs:type_name -> mmn.TxMeta
	1, // 2: mmn.AccountService.GetAccount:input_type -> mmn.GetAccountRequest
	3, // 3: mmn.AccountService.GetTxHistory:input_type -> mmn.GetTxHistoryRequest
	6, // 4: mmn.AccountService.GetCurrentNonce:input_type -> mmn.GetCurrentNonceRequest
	2, // 5: mmn.AccountService.GetAccount:output_type -> mmn.GetAccountResponse
	5, // 6: mmn.AccountService.GetTxHistory:output_type -> mmn.GetTxHistoryResponse
	7, // 7: mmn.AccountService.GetCurrentNonce:output_type -> mmn.GetCurrentNonceResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		EnumInfos:         file_account_proto_enumTypes,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
