// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: block.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumHashes     uint64                 `protobuf:"varint,1,opt,name=num_hashes,json=numHashes,proto3" json:"num_hashes,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Transactions  [][]byte               `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TxHashes      []string               `protobuf:"bytes,4,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetNumHashes() uint64 {
	if x != nil {
		return x.NumHashes
	}
	return 0
}

func (x *Entry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Entry) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Entry) GetTxHashes() []string {
	if x != nil {
		return x.TxHashes
	}
	return nil
}

type Block struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Slot            uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	PrevHash        []byte                 `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Entries         []*Entry               `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderId        string                 `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Timestamp       uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash            []byte                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature       []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	TransactionData []*TransactionData     `protobuf:"bytes,8,rep,name=transaction_data,json=transactionData,proto3" json:"transaction_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Block) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *Block) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Block) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *Block) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Block) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Block) GetTransactionData() []*TransactionData {
	if x != nil {
		return x.TransactionData
	}
	return nil
}

type EmptyParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyParams) Reset() {
	*x = EmptyParams{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyParams) ProtoMessage() {}

func (x *EmptyParams) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyParams.ProtoReflect.Descriptor instead.
func (*EmptyParams) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

type GetBlockByNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumbers  []uint64               `protobuf:"varint,1,rep,packed,name=block_numbers,json=blockNumbers,proto3" json:"block_numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByNumberRequest) Reset() {
	*x = GetBlockByNumberRequest{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByNumberRequest) ProtoMessage() {}

func (x *GetBlockByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByNumberRequest.ProtoReflect.Descriptor instead.
func (*GetBlockByNumberRequest) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlockByNumberRequest) GetBlockNumbers() []uint64 {
	if x != nil {
		return x.BlockNumbers
	}
	return nil
}

type GetBlockNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockNumberResponse) Reset() {
	*x = GetBlockNumberResponse{}
	mi := &file_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockNumberResponse) ProtoMessage() {}

func (x *GetBlockNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockNumberResponse.ProtoReflect.Descriptor instead.
func (*GetBlockNumberResponse) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlockNumberResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type GetBlockByNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Decimals      uint32                 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"` // Number of fractional digits for amount formatting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByNumberResponse) Reset() {
	*x = GetBlockByNumberResponse{}
	mi := &file_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByNumberResponse) ProtoMessage() {}

func (x *GetBlockByNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByNumberResponse.ProtoReflect.Descriptor instead.
func (*GetBlockByNumberResponse) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlockByNumberResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *GetBlockByNumberResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetBlockByNumberResponse) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

type BlockInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Slot            uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	PrevHash        []byte                 `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	LeaderId        string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Timestamp       uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash            []byte                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature       []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	TransactionData []*TransactionData     `protobuf:"bytes,7,rep,name=transaction_data,json=transactionData,proto3" json:"transaction_data,omitempty"` // Only transaction data, no entries
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockInfo) Reset() {
	*x = BlockInfo{}
	mi := &file_block_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfo) ProtoMessage() {}

func (x *BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfo.ProtoReflect.Descriptor instead.
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{6}
}

func (x *BlockInfo) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BlockInfo) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *BlockInfo) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *BlockInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockInfo) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockInfo) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BlockInfo) GetTransactionData() []*TransactionData {
	if x != nil {
		return x.TransactionData
	}
	return nil
}

type GetBlockByRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSlot      uint64                 `protobuf:"varint,1,opt,name=from_slot,json=fromSlot,proto3" json:"from_slot,omitempty"`
	ToSlot        uint64                 `protobuf:"varint,2,opt,name=to_slot,json=toSlot,proto3" json:"to_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByRangeRequest) Reset() {
	*x = GetBlockByRangeRequest{}
	mi := &file_block_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByRangeRequest) ProtoMessage() {}

func (x *GetBlockByRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByRangeRequest.ProtoReflect.Descriptor instead.
func (*GetBlockByRangeRequest) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlockByRangeRequest) GetFromSlot() uint64 {
	if x != nil {
		return x.FromSlot
	}
	return 0
}

func (x *GetBlockByRangeRequest) GetToSlot() uint64 {
	if x != nil {
		return x.ToSlot
	}
	return 0
}

type GetBlockByRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockInfo           `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	TotalBlocks   uint32                 `protobuf:"varint,2,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"` // Total blocks in the requested range
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Decimals      uint32                 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"` // Number of fractional digits for amount formatting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByRangeResponse) Reset() {
	*x = GetBlockByRangeResponse{}
	mi := &file_block_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByRangeResponse) ProtoMessage() {}

func (x *GetBlockByRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByRangeResponse.ProtoReflect.Descriptor instead.
func (*GetBlockByRangeResponse) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlockByRangeResponse) GetBlocks() []*BlockInfo {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *GetBlockByRangeResponse) GetTotalBlocks() uint32 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

func (x *GetBlockByRangeResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GetBlockByRangeResponse) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\x03mmn\x1a\btx.proto\"{\n" +
	"\x05Entry\x12\x1d\n" +
	"\n" +
	"num_hashes\x18\x01 \x01(\x04R\tnumHashes\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\"\n" +
	"\ftransactions\x18\x03 \x03(\fR\ftransactions\x12\x1b\n" +
	"\ttx_hashes\x18\x04 \x03(\tR\btxHashes\"\x8c\x02\n" +
	"\x05Block\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\fR\bprevHash\x12$\n" +
	"\aentries\x18\x03 \x03(\v2\n" +
	".mmn.EntryR\aentries\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\tR\bleaderId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\fR\x04hash\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12?\n" +
	"\x10transaction_data\x18\b \x03(\v2\x14.mmn.TransactionDataR\x0ftransactionData\"\r\n" +
	"\vEmptyParams\">\n" +
	"\x17GetBlockByNumberRequest\x12#\n" +
	"\rblock_numbers\x18\x01 \x03(\x04R\fblockNumbers\";\n" +
	"\x16GetBlockNumberResponse\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\"p\n" +
	"\x18GetBlockByNumberResponse\x12\"\n" +
	"\x06blocks\x18\x01 \x03(\v2\n" +
	".mmn.BlockR\x06blocks\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\rR\bdecimals\"\xea\x01\n" +
	"\tBlockInfo\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\fR\bprevHash\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\fR\x04hash\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12?\n" +
	"\x10transaction_data\x18\a \x03(\v2\x14.mmn.TransactionDataR\x0ftransactionData\"N\n" +
	"\x16GetBlockByRangeRequest\x12\x1b\n" +
	"\tfrom_slot\x18\x01 \x01(\x04R\bfromSlot\x12\x17\n" +
	"\ato_slot\x18\x02 \x01(\x04R\x06toSlot\"\x98\x01\n" +
	"\x17GetBlockByRangeResponse\x12&\n" +
	"\x06blocks\x18\x01 \x03(\v2\x0e.mmn.BlockInfoR\x06blocks\x12!\n" +
	"\ftotal_blocks\x18\x02 \x01(\rR\vtotalBlocks\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\rR\bdecimals2\xee\x01\n" +
	"\fBlockService\x12?\n" +
	"\x0eGetBlockNumber\x12\x10.mmn.EmptyParams\x1a\x1b.mmn.GetBlockNumberResponse\x12O\n" +
	"\x10GetBlockByNumber\x12\x1c.mmn.GetBlockByNumberRequest\x1a\x1d.mmn.GetBlockByNumberResponse\x12L\n" +
	"\x0fGetBlockByRange\x12\x1b.mmn.GetBlockByRangeRequest\x1a\x1c.mmn.GetBlockByRangeResponseB\x11Z\x0fmmn/proto;protob\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_block_proto_goTypes = []any{
	(*Entry)(nil),                    // 0: mmn.Entry
	(*Block)(nil),                    // 1: mmn.Block
	(*EmptyParams)(nil),              // 2: mmn.EmptyParams
	(*GetBlockByNumberRequest)(nil),  // 3: mmn.GetBlockByNumberRequest
	(*GetBlockNumberResponse)(nil),   // 4: mmn.GetBlockNumberResponse
	(*GetBlockByNumberResponse)(nil), // 5: mmn.GetBlockByNumberResponse
	(*BlockInfo)(nil),                // 6: mmn.BlockInfo
	(*GetBlockByRangeRequest)(nil),   // 7: mmn.GetBlockByRangeRequest
	(*GetBlockByRangeResponse)(nil),  // 8: mmn.GetBlockByRangeResponse
	(*TransactionData)(nil),          // 9: mmn.TransactionData
}
var file_block_proto_depIdxs = []int32{
	0, // 0: mmn.Block.entries:type_name -> mmn.Entry
	9, // 1: mmn.Block.transaction_data:type_name -> mmn.TransactionData
	1, // 2: mmn.GetBlockByNumberResponse.blocks:type_name -> mmn.Block
	9, // 3: mmn.BlockInfo.transaction_data:type_name -> mmn.TransactionData
	6, // 4: mmn.GetBlockByRangeResponse.blocks:type_name -> mmn.BlockInfo
	2, // 5: mmn.BlockService.GetBlockNumber:input_type -> mmn.EmptyParams
	3, // 6: mmn.BlockService.GetBlockByNumber:input_type -> mmn.GetBlockByNumberRequest
	7, // 7: mmn.BlockService.GetBlockByRange:input_type -> mmn.GetBlockByRangeRequest
	4, // 8: mmn.BlockService.GetBlockNumber:output_type -> mmn.GetBlockNumberResponse
	5, // 9: mmn.BlockService.GetBlockByNumber:output_type -> mmn.GetBlockByNumberResponse
	8, // 10: mmn.BlockService.GetBlockByRange:output_type -> mmn.GetBlockByRangeResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	file_tx_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
