// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: transaction_infinite.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionInfiniteResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Meta          *TransactionInfiniteMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []*TransactionItem       `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfiniteResponse) Reset() {
	*x = TransactionInfiniteResponse{}
	mi := &file_transaction_infinite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfiniteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfiniteResponse) ProtoMessage() {}

func (x *TransactionInfiniteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_infinite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfiniteResponse.ProtoReflect.Descriptor instead.
func (*TransactionInfiniteResponse) Descriptor() ([]byte, []int) {
	return file_transaction_infinite_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionInfiniteResponse) GetMeta() *TransactionInfiniteMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TransactionInfiniteResponse) GetData() []*TransactionItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type TransactionInfiniteMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextTimestamp uint64                 `protobuf:"varint,5,opt,name=next_timestamp,json=nextTimestamp,proto3" json:"next_timestamp,omitempty"`
	NextHash      string                 `protobuf:"bytes,6,opt,name=next_hash,json=nextHash,proto3" json:"next_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfiniteMeta) Reset() {
	*x = TransactionInfiniteMeta{}
	mi := &file_transaction_infinite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfiniteMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfiniteMeta) ProtoMessage() {}

func (x *TransactionInfiniteMeta) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_infinite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfiniteMeta.ProtoReflect.Descriptor instead.
func (*TransactionInfiniteMeta) Descriptor() ([]byte, []int) {
	return file_transaction_infinite_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionInfiniteMeta) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *TransactionInfiniteMeta) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TransactionInfiniteMeta) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TransactionInfiniteMeta) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *TransactionInfiniteMeta) GetNextTimestamp() uint64 {
	if x != nil {
		return x.NextTimestamp
	}
	return 0
}

func (x *TransactionInfiniteMeta) GetNextHash() string {
	if x != nil {
		return x.NextHash
	}
	return ""
}

type TransactionItem struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ChainId                  string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Hash                     string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Nonce                    uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BlockHash                string                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber              string                 `protobuf:"bytes,5,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	FromAddress              string                 `protobuf:"bytes,6,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress                string                 `protobuf:"bytes,7,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	TransactionTimestamp     uint64                 `protobuf:"varint,8,opt,name=transaction_timestamp,json=transactionTimestamp,proto3" json:"transaction_timestamp,omitempty"`
	Value                    string                 `protobuf:"bytes,9,opt,name=value,proto3" json:"value,omitempty"`
	TransactionType          int32                  `protobuf:"varint,10,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Status                   *uint64                `protobuf:"varint,11,opt,name=status,proto3,oneof" json:"status,omitempty"`
	TextData                 string                 `protobuf:"bytes,12,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	ExtraInfo                string                 `protobuf:"bytes,13,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	TransactionExtraInfoType string                 `protobuf:"bytes,14,opt,name=transaction_extra_info_type,json=transactionExtraInfoType,proto3" json:"transaction_extra_info_type,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TransactionItem) Reset() {
	*x = TransactionItem{}
	mi := &file_transaction_infinite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionItem) ProtoMessage() {}

func (x *TransactionItem) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_infinite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionItem.ProtoReflect.Descriptor instead.
func (*TransactionItem) Descriptor() ([]byte, []int) {
	return file_transaction_infinite_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionItem) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *TransactionItem) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TransactionItem) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TransactionItem) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *TransactionItem) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *TransactionItem) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TransactionItem) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransactionItem) GetTransactionTimestamp() uint64 {
	if x != nil {
		return x.TransactionTimestamp
	}
	return 0
}

func (x *TransactionItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TransactionItem) GetTransactionType() int32 {
	if x != nil {
		return x.TransactionType
	}
	return 0
}

func (x *TransactionItem) GetStatus() uint64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TransactionItem) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

func (x *TransactionItem) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

func (x *TransactionItem) GetTransactionExtraInfoType() string {
	if x != nil {
		return x.TransactionExtraInfoType
	}
	return ""
}

var File_transaction_infinite_proto protoreflect.FileDescriptor

const file_transaction_infinite_proto_rawDesc = "" +
	"\n" +
	"\x1atransaction_infinite.proto\x12\x03mmn\"y\n" +
	"\x1bTransactionInfiniteResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.mmn.TransactionInfiniteMetaR\x04meta\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.mmn.TransactionItemR\x04data\"\xbd\x01\n" +
	"\x17TransactionInfiniteMeta\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\x12%\n" +
	"\x0enext_timestamp\x18\x05 \x01(\x04R\rnextTimestamp\x12\x1b\n" +
	"\tnext_hash\x18\x06 \x01(\tR\bnextHash\"\xf3\x03\n" +
	"\x0fTransactionItem\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_number\x18\x05 \x01(\tR\vblockNumber\x12!\n" +
	"\ffrom_address\x18\x06 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\a \x01(\tR\ttoAddress\x123\n" +
	"\x15transaction_timestamp\x18\b \x01(\x04R\x14transactionTimestamp\x12\x14\n" +
	"\x05value\x18\t \x01(\tR\x05value\x12)\n" +
	"\x10transaction_type\x18\n" +
	" \x01(\x05R\x0ftransactionType\x12\x1b\n" +
	"\x06status\x18\v \x01(\x04H\x00R\x06status\x88\x01\x01\x12\x1b\n" +
	"\ttext_data\x18\f \x01(\tR\btextData\x12\x1d\n" +
	"\n" +
	"extra_info\x18\r \x01(\tR\textraInfo\x12=\n" +
	"\x1btransaction_extra_info_type\x18\x0e \x01(\tR\x18transactionExtraInfoTypeB\t\n" +
	"\a_statusB$Z\"github.com/mezonai/mmn/proto;protob\x06proto3"

var (
	file_transaction_infinite_proto_rawDescOnce sync.Once
	file_transaction_infinite_proto_rawDescData []byte
)

func file_transaction_infinite_proto_rawDescGZIP() []byte {
	file_transaction_infinite_proto_rawDescOnce.Do(func() {
		file_transaction_infinite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_infinite_proto_rawDesc), len(file_transaction_infinite_proto_rawDesc)))
	})
	return file_transaction_infinite_proto_rawDescData
}

var file_transaction_infinite_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transaction_infinite_proto_goTypes = []any{
	(*TransactionInfiniteResponse)(nil), // 0: mmn.TransactionInfiniteResponse
	(*TransactionInfiniteMeta)(nil),     // 1: mmn.TransactionInfiniteMeta
	(*TransactionItem)(nil),             // 2: mmn.TransactionItem
}
var file_transaction_infinite_proto_depIdxs = []int32{
	1, // 0: mmn.TransactionInfiniteResponse.meta:type_name -> mmn.TransactionInfiniteMeta
	2, // 1: mmn.TransactionInfiniteResponse.data:type_name -> mmn.TransactionItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_infinite_proto_init() }
func file_transaction_infinite_proto_init() {
	if File_transaction_infinite_proto != nil {
		return
	}
	file_transaction_infinite_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_infinite_proto_rawDesc), len(file_transaction_infinite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_infinite_proto_goTypes,
		DependencyIndexes: file_transaction_infinite_proto_depIdxs,
		MessageInfos:      file_transaction_infinite_proto_msgTypes,
	}.Build()
	File_transaction_infinite_proto = out.File
	file_transaction_infinite_proto_goTypes = nil
	file_transaction_infinite_proto_depIdxs = nil
}
