services:
  # http://localhost:8123/play <- web ui
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9440:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

 
volumes:
  clickhouse_data:
