version: '3.8'

services:
  dong-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dong-service
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8888
      SERVER_GIN_MODE: debug
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: password
      DATABASE_NAME: indexer
      DATABASE_SCHEMA: dong_schema
      DATABASE_SSLMODE: disable
      DATABASE_MAX_OPEN_CONNS: 25
      DATABASE_MAX_IDLE_CONNS: 5
      JWT_SECRET: "a75081d475a4cd4e130916f26e3e8d3ebc376fa132e873c057c5a0c5ab26cc06"
      JWT_REFRESH_EXP: 432000
      JWT_ACCESS_EXP: 3600
      OAUTH_CLIENT_ID: "1976233808680194048"
      OAUTH_CLIENT_SECRET: ">cxIm=C8v[Be0XE0@bius4UhLqu{P&8="
      OAUTH_TOKEN_URL: "https://oauth2.mezon.ai/oauth2/token"
      OAUTH_USER_INFO_URL: "https://oauth2.mezon.ai/userinfo"
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      LOGGING_LEVEL: "debug"
      LOGGING_OUTPUT: "stdout"
      LOGGING_FILE_PATH: "/app/logs/dong-service.log"
      LOGGING_MAX_SIZE: 100
      LOGGING_MAX_AGE: 30
      # Scheduler Configuration
      SCHEDULER_SYNC_CONTRIBUTORS_INTERVAL: 600
      # Indexer Configuration
      INDEXER_SCHEMA: public
      AES_SECRET_KEY: "bI+eULxtWWQooHeBB8JoJWigGxCtPzTBxGQDLcAlUuY="
    ports:
      - "8888:8888"
    volumes:
      - dong_logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  dong_logs:

