package constants

const (
	CREATE_ORDER       = "CREATE_OFFER"
	CONFIRM_ORDER      = "CONFIRM_OFFER"
	CANCEL_ORDER       = "CANCEL_OFFER"
	OFFER_LIST_REFRESH = "OFFER_LIST_REFRESH"

	ALL_RECEIVER = "*"
)
