package constants

const (
	CREATE_ORDER  = "CREATE_OFFER"
	CONFIRM_ORDER = "CONFIRM_OFFER"
	CANCEL_ORDER  = "CANCEL_OFFER"

	OFFER_LIST_REFRESH = "OFFER_LIST_REFRESH"
	OFFER_ROOM         = "offer_updates"

	ORDER_CONFIRMED = "ORDER_CONFIRMED"
	ORDER_COMPLETED = "ORDER_COMPLETED"
	ORDER_CREATED   = "ORDER_CREATED"
)
