package constants

const (
	CREATE_ORDER       = "CREATE_OFFER"
	CONFIRM_ORDER      = "CONFIRM_OFFER"
	CANCEL_ORDER       = "CANCEL_OFFER"
	OFFER_LIST_REFRESH = "OFFER_LIST_REFRESH"

	ALL_RECEIVER = "*"

	// Order events
	ORDER_CREATED   = "ORDER_CREATED"
	ORDER_CONFIRMED_EVENT = "ORDER_CONFIRMED"
	ORDER_COMPLETED_EVENT = "ORDER_COMPLETED"
)
