name: Deploy Frontend Service
permissions:
  contents: write
  
on: 
  workflow_dispatch:
    inputs:
      env:
        description: "Environment (dev|prod)"
        required: true
        default: "dev"
      ref:
        description: "Git ref (branch, tag, or commit)"
        required: true
        default: "main"
      existing_tag_to_deploy:
        description: "(Optional) Existing tag to deploy"
        required: false

  workflow_call:
    inputs:
      env:
        type: string
        required: true
      ref:
        type: string
        required: true
      target_tag:
        type: string
        required: true
      skip_build:
        type: string
        required: true
    secrets:
      NEXT_PUBLIC_COBAR_API_KEY:
        required: true
      NEXT_PUBLIC_MEZON_SERVER_KEY:
        required: true

jobs:
  build:
    runs-on: [self-hosted, Linux, mezon-runner]
    environment: ${{ inputs.env }}
    outputs:
      tag_name: ${{ steps.build_frontend.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          clean: false
          fetch-depth: 1

      - name: Setup Node.js
        if: inputs.skip_build == 'false' || inputs.existing_tag_to_deploy == ''
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: ''

      - name: Build Frontend
        if: inputs.skip_build == 'false' || inputs.existing_tag_to_deploy == ''
        id: build_frontend
        env: 
          NEXT_PUBLIC_APP_API_URL: ${{ vars.NEXT_PUBLIC_APP_API_URL }}
          APP_API_URL_INTERNAL: ${{ vars.APP_API_URL_INTERNAL }}
          NEXT_PUBLIC_CHAT_APP_MMN_API_URL: ${{ vars.NEXT_PUBLIC_CHAT_APP_MMN_API_URL }}
          NEXT_PUBLIC_CHAT_APP_ZK_API_URL: ${{ vars.NEXT_PUBLIC_CHAT_APP_ZK_API_URL }}
          NEXT_PUBLIC_BACKEND_API_URL: ${{ vars.NEXT_PUBLIC_BACKEND_API_URL }}
          NEXT_PUBLIC_OAUTH2_API_URL: ${{ vars.NEXT_PUBLIC_OAUTH2_API_URL }}
          NEXT_PUBLIC_OAUTH2_CLIENT_ID: ${{ vars.OAUTH_CLIENT_ID }}
          NEXT_PUBLIC_OAUTH2_REDIRECT_URI: ${{ vars.NEXT_PUBLIC_OAUTH2_REDIRECT_URI }}
          NEXT_PUBLIC_OAUTH2_SCOPE: ${{ vars.NEXT_PUBLIC_OAUTH2_SCOPE }}
          NEXT_BASE_FE: ${{ vars.NEXT_BASE_FE }}
          NEXT_PUBLIC_COBAR_API_URL: ${{ vars.NEXT_PUBLIC_COBAR_API_URL }}
          NEXT_PUBLIC_COBAR_API_KEY: ${{ secrets.NEXT_PUBLIC_COBAR_API_KEY }}
          NEXT_PUBLIC_TOP_MEZON_AI: ${{ vars.NEXT_PUBLIC_TOP_MEZON_AI }}
          NEXT_PUBLIC_BASE_FE: ${{ vars.NEXT_BASE_FE }}
          NEXT_PUBLIC_WEBSOCKET_URL: ${{ vars.NEXT_PUBLIC_WEBSOCKET_URL }}
          NEXT_PUBLIC_MEZON_SERVER_KEY: ${{ secrets.NEXT_PUBLIC_MEZON_SERVER_KEY }}
        run: |
          cd frontend

          rm -rf .next node_modules
          npm install
          npm run build

          mkdir -p .deploy

          cp -r .next/standalone/* .deploy/
          mkdir -p .deploy/.next
          cp -r .next/static .deploy/.next/
          cp -r public .deploy/

          cd .deploy

          TAG_NAME="${{ inputs.target_tag }}"
          if [ -z "$TAG_NAME" ]; then TAG_NAME="v0.0.0"; fi
          
          ARTIFACT_NAME="$TAG_NAME-${{ inputs.env }}"
          
          mkdir -p ../../build_frontend
          tar -czf ../../build_frontend/frontend-build-${ARTIFACT_NAME}.tar.gz .

          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Bundle
        if: inputs.skip_build == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.build_frontend.outputs.tag_name }}
          name: "Release ${{ steps.build_frontend.outputs.tag_name }}"
          target_commitish: ${{ inputs.ref }}
          fail_on_unmatched_files: true
          files: build_frontend/frontend-build-${{ steps.build_frontend.outputs.artifact_name }}.tar.gz

  deploy:
    needs: build
    if: always()
    runs-on: [self-hosted, Linux, mezon-runner]
    environment: ${{ inputs.env }}

    steps:
      - name: Determine Frontend Tag
        id: determine_tag
        run: |
          TAG_INPUT=""
          if [ -n "${{ needs.build.outputs.tag_name }}" ]; then
            TAG_INPUT="${{ needs.build.outputs.tag_name }}"
          elif [ -n "${{ inputs.existing_tag_to_deploy }}" ]; then 
            TAG_INPUT="${{ inputs.existing_tag_to_deploy }}"
          elif [ "${{ needs.build.result }}" == "success" ]; then
            TAG_INPUT="${{ needs.build.outputs.tag_name }}"
          else
            echo "::error::Cannot proceed. No existing tag was provided and the build job did not succeed."
            exit 1
          fi

          if [[ ! "$TAG_INPUT" == v* ]]; then
            TAG_TO_DEPLOY="v$TAG_INPUT"
            echo "==> Prefix 'v' was missing. Standardizing to: $TAG_TO_DEPLOY"
          else
            TAG_TO_DEPLOY="$TAG_INPUT"
          fi

          ARTIFACT_NAME="${TAG_TO_DEPLOY}-${{ inputs.env }}"

          echo "tag_name=$TAG_TO_DEPLOY" >> $GITHUB_OUTPUT
          echo "frontend_name=frontend-build-$ARTIFACT_NAME.tar.gz" >> $GITHUB_OUTPUT
          echo "frontend_path=build_frontend/frontend-build-$ARTIFACT_NAME.tar.gz" >> $GITHUB_OUTPUT

      - name: Download Frontend Release Bundle
        if: inputs.existing_tag_to_deploy != ''
        run: | 
          set -e 
          OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1)
          REPO=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)
          TAG_NAME="${{ steps.determine_tag.outputs.tag_name }}"
          FRONTEND_NAME="${{ steps.determine_tag.outputs.frontend_name }}"
          FRONTEND_PATH="${{ steps.determine_tag.outputs.frontend_path }}"

          DOWNLOAD_URL="https://github.com/${OWNER}/${REPO}/releases/download/${TAG_NAME}/${FRONTEND_NAME}"

          echo "==> Downloading Frontend Bundle from: $DOWNLOAD_URL"
          
          mkdir -p build_frontend

          curl -sSL --fail -L -o "$FRONTEND_PATH" "$DOWNLOAD_URL"


      - name: Generate remote setup script
        env:
          NEXT_PUBLIC_APP_API_URL: ${{ vars.NEXT_PUBLIC_APP_API_URL }}
          APP_API_URL_INTERNAL: ${{ vars.APP_API_URL_INTERNAL }}
          NEXT_PUBLIC_CHAT_APP_MMN_API_URL: ${{ vars.NEXT_PUBLIC_CHAT_APP_MMN_API_URL }}
          NEXT_PUBLIC_CHAT_APP_ZK_API_URL: ${{ vars.NEXT_PUBLIC_CHAT_APP_ZK_API_URL }}
          NEXT_PUBLIC_BACKEND_API_URL: ${{ vars.NEXT_PUBLIC_BACKEND_API_URL }}
          NEXT_PUBLIC_OAUTH2_API_URL: ${{ vars.NEXT_PUBLIC_OAUTH2_API_URL }}
          NEXT_PUBLIC_OAUTH2_CLIENT_ID: ${{ vars.OAUTH_CLIENT_ID }}
          NEXT_PUBLIC_OAUTH2_REDIRECT_URI: ${{ vars.NEXT_PUBLIC_OAUTH2_REDIRECT_URI }}
          NEXT_PUBLIC_OAUTH2_SCOPE: ${{ vars.NEXT_PUBLIC_OAUTH2_SCOPE }}
          NEXT_BASE_FE: ${{ vars.NEXT_BASE_FE }}
          NEXT_PUBLIC_COBAR_API_URL: ${{ vars.NEXT_PUBLIC_COBAR_API_URL }}
          NEXT_PUBLIC_COBAR_API_KEY: ${{ secrets.NEXT_PUBLIC_COBAR_API_KEY }}
          NEXT_PUBLIC_TOP_MEZON_AI: ${{ vars.NEXT_PUBLIC_TOP_MEZON_AI }}
          NEXT_PUBLIC_BASE_FE: ${{ vars.NEXT_BASE_FE }}
          NEXT_PUBLIC_WEBSOCKET_URL: ${{ vars.NEXT_PUBLIC_WEBSOCKET_URL}}
          NEXT_PUBLIC_MEZON_SERVER_KEY: ${{ secrets.NEXT_PUBLIC_MEZON_SERVER_KEY }}
        run: |
          printenv | grep -E '^(NEXT_|APP_)' > frontend.env

      - name: Prepare and deploy to target server
        run: |
          set -e
          echo "==> Copying env file to target server..."
          scp -i ${{ vars.SSH_PRIVATE_KEY_PATH }} frontend.env ${{ vars.HOST_ALIAS }}:/tmp/frontend_tmp.env 

          echo "==> Copying frontend bundle..."
          scp -i ${{ vars.SSH_PRIVATE_KEY_PATH }} ${{ steps.determine_tag.outputs.frontend_path }} ${{ vars.HOST_ALIAS }}:/tmp/frontend.tar.gz

          echo "==> Applying configuration on server..."
          ssh -i ${{ vars.SSH_PRIVATE_KEY_PATH }} ${{ vars.HOST_ALIAS}} "
            set -e 
            echo '==> Extracting frontend bundle'
            sudo rm -rf /opt/frontend/.next/standalone/*
            sudo mkdir -p /opt/frontend/.next/standalone

            sudo tar -xzf /tmp/frontend.tar.gz -C /opt/frontend/.next/standalone

            echo '==> Updating /opt/frontend/...'
            sudo mv /tmp/frontend_tmp.env /opt/frontend/frontend.env
            sudo chown mmn:mmn /opt/frontend/frontend.env
            sudo chmod 600 /opt/frontend/frontend.env

            sudo rm -f /tmp/frontend_tmp.env
            sudo rm -f /tmp/frontend.tar.gz
            "

      - name: Atomic swap + restart services
        run: |
          ssh -i ${{vars.SSH_PRIVATE_KEY_PATH}} ${{vars.HOST_ALIAS}} <<EOF
          #!/usr/bin/env bash
          set -euo pipefail

          echo '==> Stopping frontend service...'
          sudo systemctl stop frontend-explorer || true

          echo "==> Reloading and starting services..."
          sudo systemctl daemon-reload
          sudo systemctl start frontend-explorer

          echo "==> Reloading Nginx..."
          sudo nginx -t && sudo systemctl reload nginx

          echo "==> Activation complete!"
          EOF

      - name: Health check after deployment 
        run: |
          echo "==> Checking Frontend status..."
          ssh -i ${{ vars.SSH_PRIVATE_KEY_PATH }} ${{ vars.HOST_ALIAS }} "systemctl is-active frontend-explorer"